const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const root=require('node:path').resolve(__dirname,'..'),Catalog=require(root+'/src/catalog.js'),C=require(root+'/src/core.js');
const closed=()=>Array.from({length:7},()=>({status:'closed',spans:[]}));
const record={name:'測試食堂',address:'板橋測試地址',phone:'02-1234-5678',location:{lat:25.0143,lng:121.4638},category:'台式',budget:130,covered:'yes',mapsUrl:'https://maps.app.goo.gl/example',weeklyHours:closed()};
assert.equal(C.opening(Catalog.hydrate(record),'12:00','13:00',new Date('2026-09-15T04:00Z')).today,false);
let hours=closed();hours[2]={status:'open',spans:[{from:'11:00',to:'14:00'},{from:'17:00',to:'20:00'}]};
assert.equal(C.opening(Catalog.hydrate({...record,weeklyHours:hours}),'12:00','13:00',new Date('2026-09-15T04:00Z')).lunch,true);
assert.equal(C.opening(Catalog.hydrate({...record,weeklyHours:hours}),'13:00','18:00',new Date('2026-09-15T04:00Z')).lunch,false);
hours[2]={status:'unknown',spans:[]};assert.equal(C.opening(Catalog.hydrate({...record,weeklyHours:hours}),'12:00','13:00',new Date('2026-09-15T04:00Z')).today,null);
for(const bad of [{location:{lat:NaN,lng:1}},{location:{lat:91,lng:1}},{phone:'<script>'},{mapsUrl:'https://www.google.com.evil.test/maps/abc'},{mapsUrl:'javascript:alert(1)'},{budget:'150'},{weeklyHours:[]}])assert.throws(()=>Catalog.validate({...record,...bad}));
assert.equal(Catalog.fingerprint({...record,name:' 測 試食堂 '}),Catalog.fingerprint(record));
const fixture=require('./server-fixture.cjs')(),{box,data,props,cache}=fixture;
box.listCandidates();
assert.throws(()=>box.addCandidate(record),/AUTH_REQUIRED/);assert.equal(data.length,1);
assert.throws(()=>box.addCandidate(record,'x'.repeat(72)),/AUTH_REQUIRED/);assert.equal(data.length,1);
assert.throws(()=>box.adminLogin('wrong'),/不正確/);
const session=box.adminLogin(props.get('ADMIN_PASSPHRASE'));
assert.equal(box.addCandidate(record,session.token).duplicate,false);assert.equal(box.addCandidate({...record,name:'測 試食堂'},session.token).duplicate,true);assert.equal(data.length,2);
box.addCandidate({...record,name:'=IMPORTXML("bad")'},session.token);assert(data[2][1].startsWith("'="));assert.equal(box.listCandidates()[1].name,'=IMPORTXML("bad")');assert.equal(fixture.held(),false);
assert(!JSON.stringify(box.getBootstrap()).includes(props.get('ADMIN_PASSPHRASE')));
assert(!JSON.stringify(box.listCandidates()).includes(session.token));
box.adminLogout(session.token);assert.throws(()=>box.addCandidate(record,session.token),/AUTH_REQUIRED/);
const expired=box.adminLogin(props.get('ADMIN_PASSPHRASE'));fixture.advance(30*60*1000+1);assert.throws(()=>box.addCandidate(record,expired.token),/AUTH_REQUIRED/);
const changed=box.adminLogin(props.get('ADMIN_PASSPHRASE'));props.set('ADMIN_PASSPHRASE','new-fixture-only-passphrase-54321');assert.throws(()=>box.addCandidate(record,changed.token),/AUTH_REQUIRED/);
const evicted=box.adminLogin(props.get('ADMIN_PASSPHRASE'));cache.clear();assert.throws(()=>box.addCandidate(record,evicted.token),/AUTH_REQUIRED/);
for(let i=0;i<10;i++)assert.throws(()=>box.adminLogin('wrong'),/不正確/);
assert.throws(()=>box.adminLogin(props.get('ADMIN_PASSPHRASE')),/頻繁/);fixture.advance(10*60*1000+1);assert(box.adminLogin(props.get('ADMIN_PASSPHRASE')).token);
props.delete('ADMIN_PASSPHRASE');assert.equal(box.getBootstrap().adminConfigured,false);assert.throws(()=>box.adminLogin('anything'),/尚未設定/);assert.throws(()=>box.addCandidate(record,changed.token),/AUTH_REQUIRED/);
assert.equal(box.getBootstrap().mapsKey,undefined);assert(!/places\.googleapis|maps\.googleapis|MAPS_BROWSER_KEY|PLACES_SERVER_KEY/.test(fs.readFileSync(root+'/dist/Code.gs','utf8')));
assert.deepEqual(JSON.parse(fs.readFileSync(root+'/dist/appsscript.json','utf8')).oauthScopes,['https://www.googleapis.com/auth/spreadsheets','https://www.googleapis.com/auth/script.external_request']);
console.log('PASS catalog and server: unauthenticated/forged/expired/revoked/rotated/evicted credentials rejected, persistent throttle, no secret disclosure, append-only, dedupe, schedule, formula safety, zero paid API.');
