const assert=require('node:assert/strict'),crypto=require('node:crypto');
const createFixture=require('./server-fixture.cjs');
const f=createFixture(),{box,props,cache}=f;
assert.throws(()=>box.beginGoogleSignIn(),/尚未準備/);
f.configureGoogle();
const pending=box.beginGoogleSignIn(),url=new URL(pending.url);
assert.equal(url.origin,'https://accounts.google.com');
assert.equal(url.searchParams.get('scope'),'openid email profile');
assert.equal(url.searchParams.get('code_challenge_method'),'S256');
assert(!pending.url.includes(props.get('GOOGLE_CLIENT_SECRET')));
assert.equal(box.getGoogleSignInResult(pending.state,pending.pollToken).status,'pending');
assert.throws(()=>box.getGoogleSignInResult(pending.state,'x'.repeat(72)),/失效/);
f.setActiveUser('another-browser-user');assert.throws(()=>box.completeGoogleSignIn_({state:pending.state,code:'fixture-code'}),/失效/);assert.equal(f.requests.length,0);
f.setActiveUser('fixture-google-browser');
f.setIdentity({sub:'member-a',email:'a@example.test',email_verified:true,name:'Alice'});
box.completeGoogleSignIn_({state:pending.state,code:'fixture-code'});
const member=box.getGoogleSignInResult(pending.state,pending.pollToken).member;
assert.equal(member.email,'a@example.test');assert.equal(member.name,'Alice');
assert.equal(box.getGoogleSignInResult(pending.state,pending.pollToken).member.token,member.token); // retry-safe poll
assert.equal(f.requests.length,2);
const exchange=f.requests[0].options.payload;
assert.equal(crypto.createHash('sha256').update(exchange.code_verifier).digest('base64url'),url.searchParams.get('code_challenge'));
assert.equal(f.requests[1].options.headers.Authorization,'Bearer fixture-google-access-token');
assert.throws(()=>box.completeGoogleSignIn_({state:pending.state,code:'replayed'}),/已處理/);
assert.equal(f.requests.length,2);
assert.equal(box.saveMemberNickname('  午餐王  ',member.token).nickname,'午餐王');
assert.throws(()=>box.saveMemberNickname('x'.repeat(33),member.token),/32/);
assert.throws(()=>box.saveMemberNickname('bad\nname',member.token),/換行/);
f.setActiveUser('another-browser-user');assert.throws(()=>box.saveMemberNickname('fake',member.token),/MEMBER_REQUIRED/);f.setActiveUser('fixture-google-browser');
const input={name:'Identity Test',address:'',phone:'',location:{lat:25.0143,lng:121.4638},category:'其他',diet:'unknown',budget:null,covered:'unknown',mapsUrl:'',weeklyHours:Array.from({length:7},()=>({status:'unknown',spans:[]}))};
const admin=box.adminLogin(props.get('ADMIN_PASSPHRASE')).token,restaurant=box.addCandidate(input,admin).record;
const reviewInput={restaurantId:restaurant.id,item:'飯',feedback:'好吃',score:100,requestId:crypto.randomUUID(),authorEmail:'forged@example.test'};
assert.throws(()=>box.addReview(reviewInput,null),/MEMBER_REQUIRED/);
const review=box.addReview(reviewInput,member.token).review;
assert.equal(review.authorLabel,'午餐王');assert.equal(review.verifiedAccount,true);
assert.equal(f.sheets.get('Reviews').data[1][8],'a@example.test');
assert(!JSON.stringify(box.listReviews(restaurant.id,null)).includes('a@example.test'));
assert(!JSON.stringify(box.listReviews(restaurant.id,null)).includes('forged@example.test'));
box.setReviewVote(review.id,1,member.token);
const secondDevice=f.issueMember('member-a','a@example.test');
assert.equal(box.setReviewVote(review.id,1,secondDevice.token).likes,1);
assert.equal(box.listReviews(restaurant.id,secondDevice.token).reviews[0].myVote,1);
assert.throws(()=>box.setReviewVote(review.id,1,null),/MEMBER_REQUIRED/);
assert.throws(()=>box.addCandidate(input,member.token),/AUTH_REQUIRED/);
box.memberLogout(secondDevice.token);assert.throws(()=>box.saveMemberNickname('',secondDevice.token),/MEMBER_REQUIRED/);
f.advance(7200001);assert.throws(()=>box.saveMemberNickname('',member.token),/MEMBER_REQUIRED/);
const invalid=createFixture();invalid.configureGoogle();invalid.setIdentity({sub:'bad',email:'x@example.test',email_verified:false});
const attempt=invalid.box.beginGoogleSignIn();assert.throws(()=>invalid.box.completeGoogleSignIn_({state:attempt.state,code:'code'}),/未完成/);assert.throws(()=>invalid.box.getGoogleSignInResult(attempt.state,attempt.pollToken),/未完成/);assert(!invalid.sheets.has('Members'));
const old=createFixture();const rid=old.box.addCandidate(input,old.box.adminLogin(old.props.get('ADMIN_PASSPHRASE')).token).record.id;
const legacyId=crypto.randomUUID();old.makeSheet('Reviews',[
 ['id','restaurant_id','item','feedback','score','author_key','request_id','created_at'],
 [legacyId,rid,'以前吃的','舊心得',100,'old-browser-hash',crypto.randomUUID(),'2026-09-01T00:00:00Z']
]);
const before=JSON.stringify(old.sheets.get('Reviews').data[1]);
const legacy=old.box.listReviews(rid,null).reviews[0];
assert.equal(legacy.id,legacyId);assert.equal(legacy.authorLabel,'以前的匿名食友');assert.equal(legacy.verifiedAccount,false);
assert.equal(old.sheets.get('Reviews').data[0].length,12);assert.equal(JSON.stringify(old.sheets.get('Reviews').data[1]),before);
assert.equal(f.held(),false);assert.equal(old.held(),false);
const numeric=createFixture(),longSub='123456789012345678901';
const numericMember=numeric.issueMember(longSub);
numeric.box.saveMemberNickname('保留暱稱',numericMember.token);
assert.equal(numeric.sheets.get('Members').data[1][0],'google:'+longSub);
assert.equal(numeric.issueMember(longSub).nickname,'保留暱稱');
assert.equal(numeric.sheets.get('Members').data.length,2);
numeric.props.set('GOOGLE_CLIENT_SECRET','fixture-rotated-secret');
assert.throws(()=>numeric.box.saveMemberNickname('',numericMember.token),/MEMBER_REQUIRED/);
console.log('PASS identity: Google code flow, PKCE, active-user binding, replay rejection, verified email, optional nickname, private email, account votes, expiry/logout, legacy review migration.');
